osx_image: xcode61
language: objective-c
before_install: gem install cocoapods xcpretty slather -N
cache: cocoapods
podfile: Example/Podfile
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - set -o pipefail && xcodebuild -workspace 'Example/Espressos.xcworkspace' -scheme 'Espressos'
    -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6"
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES clean test | xcpretty -c
  - pod lib lint --quick
after_success: slather
